blank_issues_enabled: false
contact_links:
  - name: "Support"
    url: "mailto:asaminewyared@gmail.com"
    about: "Contact support for assistance."
  - name: "You may need this!"
    url: "mailto:senait.bek@gmail.com"
    about: "YOU MAY NEED THIS! EH?"